[phases.setup]
nixPkgs = ["nodejs_25"]

[phases.install]
cmds = [
  "node --version",
  "npm --version",
  "npm ci"
]

[phases.build]
cmds = [
  "node --version",
  "npm run build"
]

[start]
cmd = "npm start"